export * from "./User";
export { default as getPokemonsIdOrName } from "./controllersApi/getPokemonsIdOrName";
export * from "./deletePokemon";
export { default as findNameInDb } from "./findNameInDb";
export { default as getAllPokemons } from "./getAllPokemons";
export { default as getPokemonIdInDb } from "./getPokemonIdInDb";
export * from "./getPokemons";
export { default as getPokemonsDb } from "./getPokemonsDb";
export { default as getTypes } from "./getTypes";
export * from "./getUsers";
export { default as newPokemon } from "./newPokemon";
