export { default as About } from "./About/About";
export { default as Detail } from "./Detail/Detail";
export * from "./Detail/SliderDetail";
export { default as Favorites } from "./Favorites/Favorites";
export { default as ContainerInfo } from "./Home/ContainerInfo/ContainerInfo";
export { default as Home } from "./Home/Home";
export { default as RenderPokemonByName } from "./Home/SearchName/RenderPokemonByName";
export { default as LoginButton } from "./Profile/LoginButton/LoginButton";
export { default as LogoutButton } from "./Profile/LogoutButton/LogoutButton";
export * from "./Profile";
