export { default as CardPokemon } from "./CardPokemon/CardPokemon";
export * from "./NavBar/Search/CssSearch";
export { default as SearchBar } from "./NavBar/Search/SearchBar";
export * from "./NavBar";
export * from "./Styles/AboutCss";
export * from "./Styles/CardStyle";
export * from "./Styles/ContainerInfoCss";
export * from "./Styles/Detail";
export * from "./Styles/Favorite";
export * from "./Styles/HomeStyle";
export * from "./Styles/NavBar";
export * from "./Styles/Styles";
export { default as Switch } from "./Switch/Switch";
